### ISSUE TITLE
Move to Angular 2

### ISSUE THREAD

**Issue by fmoliveira** [fmoliveira/tantalus#35]
Tantalus is still a small application, so, it seems the perfect timing to move it to Angular 2.

Many Evernote users have got thousands of notes in their accounts, so, performance is a critical factor for Tantalus. Angular 2 has proven to be superior in terms of performance than its predecessor.

**Comment by kmf** [comment]
+1

**Comment by Tammuz** [comment]
Is this project still active? Sounds interesting

**Comment by fmoliveira** [comment]
Hi @Tammuz , yep, the idea is still very active but unfortunately I hadn't the time to work on it lately. But it's surely alive. :)

Though, I regret on opening this issue to move to Angular 2. I've been working with it since July 2016 and I'm very frustrated with the framework. It'll probably be moved to React instead. But I'll close this issue for now and make the app itself work in the current frontend, which has the basic features working already.

The project should move faster with this one closed for now. It'll be revisited when the app works. :)
