### ISSUE TITLE
Vala

### ISSUE THREAD

**Issue by fmoliveira** [fmoliveira/tantalus#6]
I'm studying [Vala](https://github.com/fmoliveira/learning-book/issues/13) to understand its potential.

Perhaps Tantalus might be written in Vala to follow elementary OS patterns, I'm not sure yet.

**Comment by fmoliveira** [comment]
Bump!

**Comment by fmoliveira** [comment]
I'll stick to Electron for now. I'm already studying so many things at the moment.

**Comment by Tammuz** [comment]
That would be so cool!!
